In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
from selenium import webdriver

ImportError: cannot import name 'WebElement'

In [2]:
url = 'https://www.dol.gov/whd/state/stateMinWageHis.htm'
response = requests.get(url).text
soup = BeautifulSoup(response)
tables = soup.find_all('table')
wages = pd.read_html(response)
wage = wages[-1]
wage = wage.drop(columns=[1, 2, 4])
wage = wage.drop([0])
wage = wage.drop([53])
wage = wage.drop([54])
wage = wage.drop([55])
wage = wage.rename(index=str, columns={0:"state", 3:'wage2016'})
wage = wage.sort_values(by='wage2016').reset_index()

   index                 state      wage2016
0     19             Louisiana           ...
1      2               Alabama           ...
2     25           Mississippi           ...
3     41        South Carolina           ...
4     43             Tennessee           ...
5     22         Massachusetts         10.00
6      6            California         10.00
7     52  District of Columbia         11.50
8     37              Oklahoma  2.00-7.25(g)
9     51               Wyoming          5.15
10    11               Georgia       5.15(d)
11    45                  Utah          7.25
12    35          North Dakota          7.25
13    34        North Carolina          7.25
14    30         New Hampshire          7.25
15    50             Wisconsin          7.25
16    44                 Texas          7.25
17    39          Pennsylvania          7.25
18     1        Federal (FLSA)          7.25
19    17                Kansas          7.25
20    18              Kentucky          7.25
21    16                  Iowa          7.25
22    13                 Idaho          7.25
23    15               Indiana       7.25(e)
24    36                  Ohio     7.25-8.10
25    29                Nevada     7.25-8.25
26    24             Minnesota  7.25-9.50(g)
27    47              Virginia       7.25[c]
28    32            New Mexico          7.50
29    20                 Maine          7.50
30    26              Missouri          7.65
31     5              Arkansas       8.00[c]
32     4               Arizona          8.05
33    10               Florida          8.05
34    27               Montana       8.05(g)
35     9              Delaware          8.25
36    14              Illinois       8.25[c]
37     7              Colorado          8.31
38    31            New Jersey          8.38
39    12                Hawaii          8.50
40    23              Michigan       8.50(e)
41    42          South Dakota          8.55
42    21              Maryland          8.75
43    49         West Virginia          8.75
44    33              New York          9.00
45    28              Nebraska       9.00[c]
46    48            Washington          9.47
47    40          Rhode Island          9.60
48     8           Connecticut          9.60
49    46               Vermont       9.60(e)
50     3                Alaska          9.75
51    38                Oregon          9.75

In [3]:
wage['wage2016'] = [x.split('(')[0] for x in wage['wage2016']]
wage['wage2016'] = [x.split('[')[0] for x in wage['wage2016']]

   index                 state   wage2016
0     19             Louisiana        ...
1      2               Alabama        ...
2     25           Mississippi        ...
3     41        South Carolina        ...
4     43             Tennessee        ...
5     22         Massachusetts      10.00
6      6            California      10.00
7     52  District of Columbia      11.50
8     37              Oklahoma  2.00-7.25
9     51               Wyoming       5.15
10    11               Georgia       5.15
11    45                  Utah       7.25
12    35          North Dakota       7.25
13    34        North Carolina       7.25
14    30         New Hampshire       7.25
15    50             Wisconsin       7.25
16    44                 Texas       7.25
17    39          Pennsylvania       7.25
18     1        Federal (FLSA)       7.25
19    17                Kansas       7.25
20    18              Kentucky       7.25
21    16                  Iowa       7.25
22    13                 Idaho       7.25
23    15               Indiana       7.25
24    36                  Ohio  7.25-8.10
25    29                Nevada  7.25-8.25
26    24             Minnesota  7.25-9.50
27    47              Virginia       7.25
28    32            New Mexico       7.50
29    20                 Maine       7.50
30    26              Missouri       7.65
31     5              Arkansas       8.00
32     4               Arizona       8.05
33    10               Florida       8.05
34    27               Montana       8.05
35     9              Delaware       8.25
36    14              Illinois       8.25
37     7              Colorado       8.31
38    31            New Jersey       8.38
39    12                Hawaii       8.50
40    23              Michigan       8.50
41    42          South Dakota       8.55
42    21              Maryland       8.75
43    49         West Virginia       8.75
44    33              New York       9.00
45    28              Nebraska       9.00
46    48            Washington       9.47
47    40          Rhode Island       9.60
48     8           Connecticut       9.60
49    46               Vermont       9.60
50     3                Alaska       9.75
51    38                Oregon       9.75

In [4]:
wage.wage2016[0] = 7.25
wage.wage2016[1] = 7.25
wage.wage2016[2] = 7.25
wage.wage2016[3] = 7.25
wage.wage2016[4] = 7.25
wage.wage2016[8] = 7.25
wage.wage2016[9] = 7.25
wage.wage2016[10] = 7.25
wage.wage2016[24] = 8.10
wage.wage2016[25] = 8.25
wage.wage2016[26] = 9.50

In [5]:
wage

   index                 state wage2016
0     19             Louisiana     7.25
1      2               Alabama     7.25
2     25           Mississippi     7.25
3     41        South Carolina     7.25
4     43             Tennessee     7.25
5     22         Massachusetts    10.00
6      6            California    10.00
7     52  District of Columbia    11.50
8     37              Oklahoma     7.25
9     51               Wyoming     7.25
10    11               Georgia     7.25
11    45                  Utah     7.25
12    35          North Dakota     7.25
13    34        North Carolina     7.25
14    30         New Hampshire     7.25
15    50             Wisconsin     7.25
16    44                 Texas     7.25
17    39          Pennsylvania     7.25
18     1        Federal (FLSA)     7.25
19    17                Kansas     7.25
20    18              Kentucky     7.25
21    16                  Iowa     7.25
22    13                 Idaho     7.25
23    15               Indiana     7.25
24    36                  Ohio      8.1
25    29                Nevada     8.25
26    24             Minnesota      9.5
27    47              Virginia     7.25
28    32            New Mexico     7.50
29    20                 Maine     7.50
30    26              Missouri     7.65
31     5              Arkansas     8.00
32     4               Arizona     8.05
33    10               Florida     8.05
34    27               Montana     8.05
35     9              Delaware     8.25
36    14              Illinois     8.25
37     7              Colorado     8.31
38    31            New Jersey     8.38
39    12                Hawaii     8.50
40    23              Michigan     8.50
41    42          South Dakota     8.55
42    21              Maryland     8.75
43    49         West Virginia     8.75
44    33              New York     9.00
45    28              Nebraska     9.00
46    48            Washington     9.47
47    40          Rhode Island     9.60
48     8           Connecticut     9.60
49    46               Vermont     9.60
50     3                Alaska     9.75
51    38                Oregon     9.75

In [6]:
wage['wage2016'] = wage.wage2016.astype(float)

index        object
state        object
wage2016    float64
dtype: object

In [7]:
wage.to_csv('minwage.csv')